algoritmo "semnome"
//. Ler uma temperatura em graus Celsius e apresentá-la convertida em graus
//Fahrenheit.A fórmula de conversão é:F=(9*C+160) / 5, sendo F a temperatura
//em Fahrenheit e C a temperatura em Celsius.



var

f,c : real

inicio
escreval("Digite a temperatura gruas Celsius :")
leia(c)
F<-(9*c+160)/5
escreva("A temperatura convertida para Fahrenheit é:")
escreval(f,"Fº")


fimalgoritmo
